### ISSUE TITLE
No activation operation error

### ISSUE THREAD

**Issue by yasersakkaf** [Breta01/handwriting-ocr#12]
In OCR.ipynb for any Classifier other than the charclass this is error we get.

`INFO:tensorflow:Restoring parameters from models/word-clas/en/CTC/Classifier
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-42-2bde6ba64949> in <module>()
----> 1 charClass = Graph(MODEL_LOC)

~\handwriting-ocr-master\ocr\tfhelpers.py in __init__(self, loc, operation, input_name)
     22             saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)
     23             saver.restore(self.sess, loc)
---> 24             self.op = self.graph.get_operation_by_name(operation).outputs[0]
     25 
     26     def run(self, data):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in get_operation_by_name(self, name)
   3161       raise TypeError("Operation names are strings (or similar), not %s." %
   3162                       type(name).__name__)
-> 3163     return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
   3164 
   3165   def _get_operation_by_name_unsafe(self, name):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in as_graph_element(self, obj, allow_tensor, allow_operation)
   3033 
   3034     with self._lock:
-> 3035       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   3036 
   3037   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   3093         if name not in self._nodes_by_name:
   3094           raise KeyError("The name %s refers to an Operation not in the "
-> 3095                          "graph." % repr(name))
   3096         return self._nodes_by_name[name]
   3097 

KeyError: "The name 'activation' refers to an Operation not in the graph."`

**Comment by yasersakkaf** [comment]
This was solved.

**Comment by haripranavk** [comment]
I'm facing the same issue. How did you solve it?

**Comment by yasersakkaf** [comment]
@haripranavk , This was long back. I think of you download the recent code it wont give you any problem

**Comment by haripranavk** [comment]
@yasersakkaf thank you for being prompt. Actually, I recently downloaded and the issue is still pertaining. 
Would you kindly let me know how did you solve?

**Comment by yasersakkaf** [comment]
Actually the OCR.ipynb was designed to use only charclass model, since here we segment the image into each character (using the gap classifier model) depending on the gaps between them.
So no other models will work.

@Breta01 Please correct me if I am wrong.

**Comment by Breta01** [comment]
@yasersakkaf yes you are correct.
The problem is that for loading models I am using my custom class `Graph`. This class use operation called `activation` as default output operation in the TensorFlow model. However, CTC model have different name of output function, which you have to specify during creation of class as: 

`model = Graph(MODEL_LOC, 'word_prediction')`

But you would also have to change mechanism of feeding images into the model. This is actually implemented in `OCR-Evaluator.ipynb` where I am comparing different models
